### ISSUE TITLE
Doesn't work as described in README: `log.logSync(logName).write(log.entry(metadata, payload))`

### ISSUE THREAD

**Issue by chriscalo** [googleapis/nodejs-logging#1266]
The behavior of `log.logSync(logName).write(log.entry(metadata, payload))` doesn't match what's described in the README.

#### Environment details

  - OS: Google App Engine Standard Environment for Node.js
  - Node.js version: 16
  - npm version: 
  - `@google-cloud/logging` version: 9.8.3

I've created a reproduction at https://github.com/chriscalo/logsync-bug and copied the full details here:

## Steps:
1. Deploy to App Engine Standard environment:

``` sh
gcloud app deploy app.yaml --project=<PROJECT_ID>
```

2. Go to [console.cloud.google.com/logs/](http://console.cloud.google.com/logs/) to view output

## Expected:

Here are the first two calls to `log.write()` in `index.js`:

``` js
const metadata = {
  resource: {
    type: "gae_app",
    labels: {
      module_id: process.env.GAE_SERVICE,
      version_id: process.env.GAE_VERSION,
    },
  },
};

log.write(log.entry(metadata, "A text payload"));
log.write(log.entry(metadata, { message: "A JSON payload" }));
```

The expected output is something like: (irrelevant details removed)

``` json
[
  {
    "textPayload": "A text payload",
    "resource": {
      "type": "gae_app",
      "labels": {
        "version_id": "logsync-bug",
        "module_id": "default",
      }
    },
    "timestamp": "2022-05-06T23:13:23.002Z",
    "logName": "projects/REDACTED_PROJECT_ID/logs/my_log"
  },
  {
    "jsonPayload": {
      "message": "A JSON payload"
    },
    "resource": {
      "type": "gae_app",
      "labels": {
        "module_id": "default",
        "version_id": "logsync-bug"
      }
    },
    "timestamp": "2022-05-06T23:13:23.004Z",
    "logName": "projects/REDACTED_PROJECT_ID/logs/my_log",
    "receiveTimestamp": "2022-05-06T23:13:23.270510336Z"
  }
]
```

## Actual:

The actual output looks like the following: (irrelevant details removed)

``` json
[
  {
    "jsonPayload": {
      "message": "A text payload",
      "timestamp": "2022-05-06T23:13:23.002Z",
      "logName": "projects/REDACTED_PROJECT_ID/logs/my_log",
      "resource": {
        "type": "gae_app",
        "labels": {
          "module_id": "default",
          "version_id": "logsync-bug"
        }
      }
    },
    "resource": {
      "type": "gae_app",
      "labels": {
        "zone": "us3",
        "version_id": "logsync-bug",
        "module_id": "default",
        "project_id": "REDACTED_PROJECT_ID"
      }
    },
    "timestamp": "2022-05-06T23:13:23.004560Z",
    "logName": "projects/REDACTED_PROJECT_ID/logs/stdout",
  },
  {
    "jsonPayload": {
      "timestamp": "2022-05-06T23:13:23.004Z",
      "message": {
        "message": "A JSON payload"
      },
      "resource": {
        "labels": {
          "module_id": "default",
          "version_id": "logsync-bug"
        },
        "type": "gae_app"
      },
      "logName": "projects/REDACTED_PROJECT_ID/logs/my_log"
    },
    "resource": {
      "type": "gae_app",
      "labels": {
        "version_id": "logsync-bug",
        "module_id": "default",
        "project_id": "REDACTED_PROJECT_ID",
        "zone": "us3"
      }
    },
    "timestamp": "2022-05-06T23:13:23.005096Z",
    "logName": "projects/REDACTED_PROJECT_ID/logs/stdout",
  }
]
```

The full output can be seen in [downloaded-logs-20220506-191603.json](https://github.com/chriscalo/logsync-bug/blob/main/downloaded-logs-20220506-191603.json)

## Fix

I've followed the instructions from the [README][], copied below. Notice that it says to create an entry, passing metadata and a payload and then call `log.write(entry)`:

[README]: https://github.com/googleapis/nodejs-logging/blob/main/README.md

```js
// Optional: Create and configure a client
const logging = new Logging();
await logging.setProjectId()
await logging.setDetectedResource()

// Create a LogSync transport, defaulting to `process.stdout`
const log = logging.logSync(logname);
const meta = { /* optional field overrides here */ };
const entry = log.entry(meta, 'Your log message');
log.write(entry);

// Syntax sugar for logging at a specific severity
log.alert(entry);
log.warning(entry);
```

However, in calls to `log.write(entry)`, it appears the final payload is being populated with the entire `entry` object passed to `log.write()` and therefore the `entry.metadata` isn't being applied at all.

So either the README is wrong or there's a bug here. To fix this it seems would require either:

1. updating the README to show how to correctly create and write to a
   `log.logSync()`, or
2. fixing the behavior to match what's in the README.

**Comment by kladnik** [comment]
I also encountered the same issue. Can't set the `logName` to something custom and also can't have `textPayload` and `jsonPayload` when using `logSync`

**Comment by losalex** [comment]
Thanks @chriscalo for opening this issue! It seems that there are multiple issues here, feel free to correct me if I am wrong:

1. I believe that having extra "message" field in jsonPayload is related to recently fixed [1301](https://github.com/googleapis/nodejs-logging/issues/1301) - we added an ability to eliminate extra "message" field when `LogSync` is used to output structured logs.
2. As for `textPayload`, I believe we only have an ability today to have text in "message" field inside `jsonPayload`. I am going to follow up on this to see how it behaves when I print raw console logs which has "textPayload" field and will get back to you.
3. As for metadata, the logic to retrieve [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) specific fields can be followed [here](https://github.com/googleapis/nodejs-logging/blob/42859ab634721cb57ca76960f8a8aa5f6dd3a987/src/entry.ts#L252).

Please let me know if my observations make sense and please comment if you have more questions.

**Comment by NeverwinterMoon** [comment]
Actually, my bad on that edit: the mentioned change (#1301) was released, so I've tried setting `useMessageField` to `false`.

It's still not behaving the same way as async `Log` does, as the end result is this:

```
{
  insertId: "INSERT ID"
  jsonPayload: {
    data: {16}
    logName: "projects/{{RETRACTED}}/logs/hyperloop-telemetry"
    resource: {2}
    timestamp: "2022-07-20T11:27:36.726Z"
    type: "BatteryStatusUpdate"
  }
  labels: {3}
  logName: "projects/{{RETRACTED}}/logs/cloudfunctions.googleapis.com%2Fcloud-functions"
  receiveTimestamp: "2022-07-20T11:27:36.839152437Z"
  resource: {2}
  timestamp: "2022-07-20T11:27:36.726459Z"
  trace: "SOME TRACE"
}
```

As you can see from the above: `logName`, `timestamp` and `resource` are still stuck under `jsonPayload`. This is clearly a bug (and is not according to the docs): at least the `logName` should actual set the value to top level, otherwise what's the point... The only thing it changed for better: `message` is no longer wrapping the data (jsonPayload#message).

**Comment by losalex** [comment]
Thanks @NeverwinterMoon for providing more context! Below are some points with respect of your observations:

1. When running in serverless environments like Cloud Functions (CF), the `logName` and `resource` fields are always overriden by the environment when stdout-based output is used. See more explanation in `Structured logging in Google Cloud` blog under [How to write logs](https://medium.com/google-cloud/structured-logging-in-google-cloud-61ee08898888.) section. I filed an issue with CF team to provide an ability to override the `logName`, so for now we embedding this into `jsonPayload` field so it could be searched at least. As for `resource`, I believe it is mandatory field and expected to be in specific format which is described [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/MonitoredResource).
2. I will follow up regarding the `timestamp` field - based on explanation [here](https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields) it should be picked up correctly from the output, but seems it might be some issues.

**Comment by losalex** [comment]
Downgrading priority for now until we clarify this issue with product teams

**Comment by losalex** [comment]
@chriscalo and @NeverwinterMoon , I was thinking to close this issue - the timestamp issue was fixed and as for `logName`, it might take time to fix - I filed a feature request for our product team and it will be tracked separately.
Please let me know if you have any other questions - thanks!

**Comment by chriscalo** [comment]
I might be misunderstanding something, but I think the original problem still stands that the docs and the behavior don't align. This would suggest that we shouldn't close this issue unless (a) there's a flaw in my original interpretation, (b) the behavior is fixed to match the docs, or (c) the docs are updated to match the behavior.

> So either the README is wrong or there's a bug here. To fix this it seems would require either:
> 
> 1. updating the README to show how to correctly create and write to a
>    `log.logSync()`, or
> 2. fixing the behavior to match what's in the README.

**Comment by cindy-peng** [comment]
Hi @chriscalo, when the logging agent pick up the logs from stdout written by LogSync, it is expected that the Logging agent then sends the structured logs to Cloud Logging as the `jsonPayload` of the [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) structure. `textPayload` will be extracted to LogEntry  parent level in very few cases, more details can be found here: https://cloud.google.com/logging/docs/structured-logging

>However, in calls to log.write(entry), it appears the final payload is being populated with the entire entry object passed to >log.write() and therefore the entry.metadata isn't being applied at all.

In your case, entry.metadata is actually still being extracted in LogEntry.resource in an extended fashion:
![image](https://github.com/googleapis/nodejs-logging/assets/148148319/034e791c-6751-4fc5-9a1b-cb6a8f2ae205)

Since by default the logging agent will [rename LogName](https://cloud.google.com/logging/docs/agent/default-logs#linux-instances) when sending to Cloud Logging API, we will still want to keep `logName` under `jsonPayload` so it is searchable before CF team provide an ability to override the logName.

I understand this is causing confusions since the logging behavior is inconsistent with log async. I will update the document to explain the expected behavior. Thank you!

**Comment by chriscalo** [comment]
I am nearly certain that the original issue as I stated it is incorrect behavior.

We might be taking past each other. Where do we think the disconnect is coming from? What more can I provide to convince the team that this behavior (or the README) is wrong.

**Comment by jordanebelanger** [comment]
@chriscalo 
I am also having trouble understanding `LogSync` and its intended purpose. 

The default behaviour of the logging object returned by logSynch is non-sensical and doesn't work in practice afaik.

The logging object must be instantiated with the `useMessageField: false` options for it generate actual logging agent/cloudrun parsable output

 i.e
```typescript
 const log = logging.logSync('test', process.stdout, {useMessageField: false})
```

**Comment by cindy-peng** [comment]
> I am nearly certain that the original issue as I stated it is incorrect behavior.
> 
> We might be talking past each other. Where do we think the disconnect is coming from? What more can I provide to convince the team that this behavior (or the README) is wrong?
> 
> Shouldn't the following be true for the `log.entry()` method?
> 
> * it should be possible to pass a string for the `payload` parameter and have that end up in the log entry as a `textPayload`
> * nothing from the `metadata` parameter should end up in the `jsonPayload`

Sorry about the confusion here Chris. I agree that there is a mismatch between the actual behavior and the README documentation for using `LogSync`. I will try a latest repro and get back to you.

**Comment by cindy-peng** [comment]
Apologize that the team has been occupied with other higher-priority work items. Will prioritize this work item for the coming quarter.

**Comment by chriscalo** [comment]
Thank you 🙏🏼 

When someone picks this up, I recommend using my reproduction repo and following the readme very closely, step-by-step.

It's not difficult, but the conversation in this issue is evidence that it's really easy to misunderstand the bug I'm trying to report.

**Comment by larssn** [comment]
I'm also extremely confused. I'm trying to get some good log outputs from a Firebase Cloud Function v2, and it spits out barely usable logs. It's very hard to figure out if the problem is this repo, cloud functions, cloud run, the cloud logging backend, etc.

Anyway, the quarter has come and gone, any updates? I realize that teams can be understaffed etc, but this issue seems to have been ongoing for over 3 years now.
