### ISSUE TITLE
"Cannot read property 'Reader' of undefined" after upgrade 8.0.1 -> 8.0.3

### ISSUE THREAD

**Issue by seriousManual** [googleapis/nodejs-logging#877]
This package is a subdependency for logging-winston (https://www.npmjs.com/package/@google-cloud/logging-winston).
We're using the latest version of logging-winston which is 4.0.0.
Since the upgrade from 8.0.1 to 8.0.3 is on the patch level it is automatically installed. My tests started failing and I was able to narrow the problem down to the automatic upgrade from 8.0.1 to 8.0.3. When I'm forcing the version of this package to be 8.0.1 the errors disappear

```
TypeError: Cannot read property 'Reader' of undefined
    at /mnt/c/dev/abc/abc/abc/src/ping/node_modules/@google-cloud/logging/build/protos/protos.js:28:29
    at /mnt/c/dev/abc/abc/abc/src/ping/node_modules/@google-cloud/logging/build/protos/protos.js:22:26
    at Object.<anonymous> (/mnt/c/dev/abc/abc/abc/src/ping/node_modules/@google-cloud/logging/build/protos/protos.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by Ezard** [comment]
This looks like it's the same issue that the PubSub library recently had: https://github.com/googleapis/nodejs-pubsub/issues/1082

**Comment by seriousManual** [comment]
absolutely, this is even happening at the same lines of code in protos.js

any suggestions for a shortterm fix?

**Comment by Ezard** [comment]
@seriousManual easiest temporary solution is to just not update to this new version I guess 😄

If you need this update, then I'd recommend deleting your `node_modules` directory and running `npm install`; this worked for me with the PubSub library, so hopefully it'll work for you too

**Comment by simonz130** [comment]
@alexander-fenster - could this be related to the batching issue?

@Ezard, @seriousManual could you try to update to the 8.0.4 package and tell me if it solves the problem? We just released it yesterday and it includes the fix to batching logic upstream that is relevant to both Pub/Sub and Logging client libraries.

**Comment by Ezard** [comment]
@simonz130 still not working for me I'm afraid

The PubSub team resolved it by updating `google-gax` to `2.7.0`: https://github.com/googleapis/nodejs-pubsub/pull/1085

**Comment by simonz130** [comment]
We need to do the same. I was under impression that this was included in 8.0.4 release, but it isn't. We'll fix it.

**Comment by seriousManual** [comment]
thanks everybody!
